<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1CCS179" failures="5" tests="26" name="ABCTest" time="0.148" errors="0" timestamp="2022-06-03T10:15:07 IST">
  <testcase classname="annotations.Example1" name="abc" time="0.004"/>
  <testcase classname="annotations.Example1" name="xyz" time="0.001"/>
  <testcase classname="demoPackageV1.SoftAssert1" name="test1" time="0.005">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [7] but found [5]
at demoPackageV1.SoftAssert1.test1(SoftAssert1.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="demoPackageV1.SoftAssert1" name="test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demoPackageV1.SoftAssert1.test2(SoftAssert1.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="demoPackageV1.Example1" name="abc" time="0.001"/>
  <testcase classname="demoPackageV1.Example1" name="xyz" time="0.001"/>
  <testcase classname="annotations.TestNGKey" name="abc" time="0.015"/>
  <testcase classname="annotations.TestNGKey" name="abc" time="0.003"/>
  <testcase classname="annotations.TestNGKey" name="abc" time="0.001"/>
  <testcase classname="annotations.TestNGKey" name="abc" time="0.003"/>
  <testcase classname="annotations.TestNGKey" name="abc" time="0.001"/>
  <testcase classname="annotations.TestNGKey" name="nop" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at annotations.TestNGKey.nop(TestNGKey.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- nop -->
  <testcase classname="annotations.TestNGKey" name="xyz" time="0.0">
    <skipped/>
  </testcase> <!-- xyz -->
  <testcase classname="annotations.Sample" name="test1" time="0.0"/>
  <testcase classname="annotations.Sample" name="test2" time="0.001"/>
  <testcase classname="annotations.Sample" name="test3" time="0.001"/>
  <testcase classname="demoPackageV1.HardAssert" name="test1" time="0.0"/>
  <testcase classname="demoPackageV1.HardAssert" name="test2" time="0.001"/>
  <testcase classname="annotations.Example2" name="f" time="0.001"/>
  <testcase classname="listeners1.Sample" name="test1" time="0.001"/>
  <testcase classname="listeners1.Sample" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at listeners1.Sample.test2(Sample.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="listeners1.Sample" name="test3" time="0.001"/>
  <testcase classname="listeners1.Sample" name="test4" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at listeners1.Sample.test4(Sample.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="demoPackageV1.Sample" name="test1" time="0.003"/>
  <testcase classname="demoPackageV1.Sample" name="test2" time="0.0"/>
  <testcase classname="demoPackageV1.Sample" name="test3" time="0.0"/>
</testsuite> <!-- ABCTest -->
